# Project: ResistAirStrikes
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o ../acllib.o Game.o
LINKOBJ  = main.o ../acllib.o Game.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libwinmm.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmsimg32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libkernel32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuser32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libgdi32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libole32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/liboleaut32.a  D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuuid.a -pg -g3
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/86188/Downloads/ACLLib-master/src"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ResistAirStrikes.exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

../acllib.o: ../acllib.c
	$(CC) -c ../acllib.c -o ../acllib.o $(CFLAGS)

Game.o: Game.c
	$(CC) -c Game.c -o Game.o $(CFLAGS)
